services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '5001:5001'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=sqlite:///instance/app.db
    volumes:
      - ./backend:/app
      - sqlite_data:/app/instance
    command: flask run --host=0.0.0.0 --port=5001

volumes:
  node_modules_frontend:
  sqlite_data:
